kind: pipeline
type: docker
name: default

steps:
  - name: fetch-tags
    image: quay.io/synpse/golang:1.16
    commands:
      - git fetch --tags
  - name: test-unit
    image: quay.io/synpse/golang:1.16
    environment:
      SYNPSE_SDK_TEST_PROJECT_NAME: synpse-go-sdk-test
      SYNPSE_SDK_TEST_PROJECT_ID: prj_21Cgc1teRUxGkvyYIxp4IQbsbe0
      SYNPSE_SDK_TEST_APPLICATION_NAME: sdk-testing-app
      SYNPSE_PROJECT_ACCESS_KEY:
        from_secret: projectAccessKey
      SYNPSE_PERSONAL_ACCESS_KEY:
        from_secret: personalAccessKey
    commands:
      - go test -v ./...